import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'

import '@repo/web-ui/styles/globals.css'
import { ViewportProvider } from '@/provider/viewport'

const dmSans = DM_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
}

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <ViewportProvider>
      <html lang='en'>
        <body className={dmSans.className}>{children}</body>
      </html>
    </ViewportProvider>
  )
}
